// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vejtorubkixfqxkewtkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlanRvcnVia2l4ZnF4a2V3dGtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzOTgwMjAsImV4cCI6MjA1MDk3NDAyMH0.gfgueHFOIpwZ1EOBpW9R4-OajjWtLm7so9S-QYv2EpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);